Fix. 검색할 장소 검색 (#11)
f-lab-edu/PlaceStory pull request #12
Opened 2024-01-10 02:36 UTC by randychoi95

- Domain layer에서 지도 검색/검색 장소에 대한 Entity를 만듦
- interactor에서 Entity를 사용하여 MapKit과 분리

2024-01-12 14:20 UTC, f-lab-max commented on PlaceStory/Domain/Sources/Entities/PlaceSearch/PlaceSearchResult.swift
> +    public let results: [MKLocalSearchCompletion]
여전히 MapKit 객체가 유출되고 있습니다.

2024-01-12 14:21 UTC, f-lab-max commented on PlaceStory/MyLocation/Sources/PlaceSearcher/PlaceSearcherViewController.swift
>  import MapKit
import MapKit은 Platform에만 있도록 해주세요

2024-01-12 14:21 UTC, f-lab-max requested changes
MapKit 의존성을 제거하는 수정이 필요합니다

2024-01-13 14:35 UTC, randychoi95 reviewed
멘토링 시간에 얘기했던 대로 MKLocalSearchCompletion 객체의 프로퍼티들을 받는 도메인 모델을 구현하여 MapKit을 분리하였습니다.

2024-01-16 17:07 UTC, nsoojin approved these changes

2024-01-16 17:07 UTC, f-lab-max approved these changes

2024-01-16 23:56 UTC, merged